### ISSUE TITLE
Hooking into dynamic methods

### ISSUE THREAD

**Issue by wimex** [csu333/Surrogate#8]
It's currently impossible to hook into a method with dynamic parameters (namely the implementation of **AsyncTask doInBackground(Void... voids)** method). Xposed is looking for an exact match, but I can't configure the method parameter types so it results in a **java.lang.NoSuchMethodError.**

**Comment by csu333** [comment]
As far as I know, dynamic parameters are just a syntactic sugar on an array so 
**AsyncTask doInBackgroup (Void... voids)** 
is just the same as
**AsyncTask doInBackground(Void[] voids)**

You should then be able to instrument those methods by considering arrays instead of dynamic parameters. Now using Surrogate this is a bit tricky because of the Reflection methods it uses. You should then use [the standard Java notation](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3). You'll find some more example here: http://stackoverflow.com/questions/5085889/l-array-notation-where-does-it-come-from

An array of Void should be represented as **[Ljava/lang/Void;**

**Comment by wimex** [comment]
Thanks for the quick reply. I didn't know the correct syntax but this seems to solve it.
